parameters:
    hwi_oauth.resource_owner.facebook.class:  Netgen\Bundle\EzSocialConnectBundle\OAuth\ResourceOwner\FacebookResourceOwner
    hwi_oauth.resource_owner.twitter.class:   Netgen\Bundle\EzSocialConnectBundle\OAuth\ResourceOwner\TwitterResourceOwner
    hwi_oauth.resource_owner.google.class:    Netgen\Bundle\EzSocialConnectBundle\OAuth\ResourceOwner\GoogleResourceOwner
    hwi_oauth.resource_owner.linkedin.class:  Netgen\Bundle\EzSocialConnectBundle\OAuth\ResourceOwner\LinkedinResourceOwner

services:
    netgen.social_connect.oauth_user_provider:
        class: Netgen\Bundle\EzSocialConnectBundle\OAuth\eZUserProvider
        parent: ezpublish.security.user_provider
        arguments:
            - "@netgen.social_connect.helper.user_content"
            - "@netgen.social_connect.repository.oauthez"
        calls:
            - [setMergeAccounts, ["$merge_accounts;netgen_social_connect$"]]
        lazy: true

    netgen.social_connect.helper.user_content:
        class: Netgen\Bundle\EzSocialConnectBundle\Helper\UserContentHelper
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.config.resolver"
            - "@ezpublish.field_helper"
            - "@netgen.social_connect.repository.oauthez"
            - "@?logger"
        calls:
            - [setFirstNameIdentifier,    ["$first_name;netgen_social_connect$"]]
            - [setLastNameIdentifier,     ["$last_name;netgen_social_connect$"]]
            - [setProfileImageIdentifier, ["$profile_image;netgen_social_connect$"]]
            - [setBaseUrls,               ['%netgen_social_connect.base_urls%']]
        lazy: true

    netgen.social_connect.controller.connect:
        class: Netgen\Bundle\EzSocialConnectBundle\Controller\ConnectController
        parent: ezpublish.controller.base

    netgen.social_connect.twig_extension:
        class: Netgen\Bundle\EzSocialConnectBundle\Twig\SocialConnectExtension
        public: false
        arguments:
            - "@netgen.social_connect.repository.oauthez"
        tags:
            - { name: twig.extension }

    netgen.social_connect.repository.oauthez:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Netgen\Bundle\EzSocialConnectBundle\Entity\OAuthEz
