language: php

cache:
    directories:
        - vendor

matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1

# test only master (+ pull requests)
branches:
  only:
    - master

# install dependencies
install:
    - phpenv config-rm xdebug.ini
    - travis_wait composer install

# execute phpunit as the script command
# only run codecov on 7.0 because it doesn't need xdebug
script:
  - if [[ ${TRAVIS_PHP_VERSION} == "5.6" ]];
     then ./vendor/bin/phpunit -d memory_limit=-1 --colors -c phpunit.xml;
     else phpdbg -qrr ./vendor/bin/phpunit -d memory_limit=-1 --colors -c phpunit.xml --coverage-clover=coverage.xml; 
    fi;

# disable mail notifications
notification:
  email: false

# increase memory limit to 3G
before_install:
    - phpenv config-add travis.php.ini

# reduce depth (history) of git checkout
git:
  depth: 30

# we don't need sudo
sudo: false

# send coverage to codecov.io
after_success:
  - if [[ ${TRAVIS_PHP_VERSION} != "5.6" ]]
    then bash <(curl -s https://codecov.io/bash);
   fi;
